swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cpuinfo"
  description: "A simple service to get disk usage/space info as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service for Disk Space"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /diskspace:
    get: 
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "DISKSPACE info"
          schema: 
            $ref: "#/definitions/DISKSPACE"
definitions:
  DISKSPACE:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"
