---
swagger: "2.0"
info:
  description: "A simple service to get disk usage/space info as an example of using\
    \ swagger-2.0 specification and codegen"
  version: "0.0.1"
  title: "cpuinfo"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service for Disk Space"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /diskspace:
    get:
      description: "Returns disk space information of the hosting server"
      operationId: "diskspace_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "DISKSPACE info"
          schema:
            $ref: "#/definitions/DISKSPACE"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  DISKSPACE:
    type: "object"
    required:
    - "model"
    properties:
      model:
        type: "string"
    example:
      model: "model"
